### ISSUE TITLE
Unable to revert  zoom in config file

### ISSUE THREAD

**Issue by julianCast** [guysoft/MagicMirrorOS#13]
I the parameter zoom in config, but after rebooting the raspberry the font size is still huge (I was testing big sizes).

**Comment by julianCast** [comment]
Exactly like this https://github.com/MichMich/MagicMirror/issues/914

**Comment by khassel** [comment]
The css setup is described [here](https://gitlab.com/khassel/magicmirror#config-modules-and-custom-css).

Can you please provide the following info's, cd into `~/magicmirror` an post the output of the following commands:
* git status
* git log -1
* docker images
* cat run/docker-compose.yml

**Comment by julianCast** [comment]
- git status:
 ```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        css/
        run/docker-compose.yml

nothing added to commit but untracked files present (use "git add" to track)
```
- git log -1:
```
commit cb7b72a62ad801c83357977f67b3a20a31f8adbe (HEAD -> master, origin/master, origin/develop, origin/HEAD)
Author: Karsten Hassel <hassel@gmx.de>
Date:   Fri May 22 23:14:15 2020 +0200

    remove obsolete ports in mmpm files [ci skip]
```
- docker images:
```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
karsten13/magicmirror   latest              4fe51b42631c        43 hours ago        528MB
```
- cat run/docker-compose.yml:
```
version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
      TZ: Europe/Berlin
    network_mode: host
    restart: unless-stopped
    command:
      - npm
      - run
      - start
```
