### ISSUE TITLE
Black screen, docker container stuck on "Restarting"

### ISSUE THREAD

**Issue by ROODAY** [guysoft/MagicMirrorOS#62]
Installed MagicMirror OS on a Raspberry Pi Model B Rev 2. I connected it to a TV and ethernet and started it up to get it going, and I saw lines printed on the TV as the Pi was booting, then the screen was black. I was able to see it show up on my network and I ssh'd into it, but I still had a black screen.

I checked the other issues here, #59 mentioned running `cat /etc/os-release`, which for me showed:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

So then I updated `/home/pi/magicmirror/run/docker-compose.yml` to look like this:
```
version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:buster
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
      - /dev/vchiq
    environment:
      DISPLAY: unix:0.0
    network_mode: host
    shm_size: "128mb"
    restart: unless-stopped
    command:
      - npm
      - run
      - start
```

Then I restarted the Pi, let it download the buster image, and I still had a black screen. I tried restarting it again, and I see this from the start logs:
```
pi@magicmirroros:~ $ cat ~/scripts/start.log
---------log-of-run_magicmirroros---------
mm is up-to-date
Pulling magicmirror ...
Pulling magicmirror ... pulling from karsten13/magicmirror
Pulling magicmirror ... digest: sha256:85737559f90cb1ee2b...
Pulling magicmirror ... status: image is up to date for k...
Pulling magicmirror ... done
mm is up-to-date
Total reclaimed space: 0B
```

At this point I checked docker, and it shows that the container is restarting, but the logs are empty:
```
pi@magicmirroros:~ $ docker ps -a
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                            PORTS     NAMES
901b8daa79b0   karsten13/magicmirror:buster   "/usr/bin/tini -- ./…"   28 minutes ago   Restarting (139) 16 seconds ago             mm
pi@magicmirroros:~ $ docker logs mm
pi@magicmirroros:~ $
```

Not sure what to try at this point.
